image: firebear/magento2

pipelines:
  default:
    - step:
        name: Check codestyle
        script:
          - ssh -o StrictHostKeyChecking=No $TESTING_SERVER -p $TESTING_PORT "./scripts/codestyle.sh $BITBUCKET_BRANCH"
    - step:
        name: Run compile
        script:
          - ssh -o StrictHostKeyChecking=No $TESTING_SERVER -p $TESTING_PORT "./scripts/compile.sh $BITBUCKET_BRANCH"
    - step:
        name: Run static tests
        script:
          - ssh -o StrictHostKeyChecking=No $TESTING_SERVER -p $TESTING_PORT "./scripts/static-tests.sh $BITBUCKET_BRANCH"
  branches:
    master:
      - parallel:
        - step:
            name: Deploy metro (CE 2.2.10)
            script:
              - ssh -o StrictHostKeyChecking=No $DEPLOY_SERVER -p $DEPLOY_PORT "./scripts/update.sh metro"
        - step:
            name: Deploy gold (CE 2.3.4)
            script:
              - ssh -o StrictHostKeyChecking=No $DEPLOY_SERVER -p $DEPLOY_PORT "./scripts/update.sh gold"
    ee:
      - parallel:
        - step:
            name: Deploy uruguay (EE 2.3.1)
            script:
              - ssh -o StrictHostKeyChecking=No $DEPLOY_SERVER -p $DEPLOY_PORT "./scripts/update.sh uruguay"
        - step:
            name: Deploy alpha (EE 2.3.4)
            script:
              - ssh -o StrictHostKeyChecking=No $DEPLOY_SERVER -p $DEPLOY_PORT "./scripts/update.sh alpha"